### ISSUE TITLE
CSS Master Issue

### ISSUE THREAD

**Issue by umerhasan17** [umerhasan17/lifehab#7]
- [ ] Panels stack on top of each other in mobile

- [ ] On-off switch labels on 1 line

- [ ] Sliders work on mobile (related to 1)

- [ ] Label fonts size down on mobile - or stack on top instead of side

- [ ] Align slider left side
